name: uber_clone_assignment
description: Ride booking simulation app
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  uuid: ^4.3.3
  google_maps_flutter: ^2.6.0
  fl_chart: ^0.66.2
  geocoding: ^2.2.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
